updated code formatting

diff --git a/qa-deployment.yaml b/qa-deployment.yaml
--- a/qa-deployment.yaml
+++ b/qa-deployment.yaml
@@ -11,14 +11,13 @@ on:
         options:
           - staging
           - production
-
-  push:
-    # branches:
-    #   - 'release/*'
-    #   - 'feature/stg-cd-integration'
-    #   - 'feature/api-automation'
-    # tags:
-    #   - 'v*.*.*'
+#  push:
+#    branches:
+#      - 'release/*'
+#      - 'feature/stg-cd-integration'
+#      - 'feature/api-automation'
+#    tags:
+#      - 'v*.*.*'
 
 jobs:
 
@@ -61,44 +60,44 @@ jobs:
           echo "Determined Topic Status: $TOPIC_STATUS"
           echo "topic_status=$TOPIC_STATUS" >> $GITHUB_OUTPUT
 
-  # copyright-check:
-  #   name: Copyright Headers Check
-  #   permissions:
-  #     contents: read
-  #     packages: read
-  #   env:
-  #     GITHUB_ACTOR: ${{ secrets.COMMON_USER }}
-  #     GITHUB_TOKEN: ${{ secrets.COMMON_USER_TOKEN }}
-  #   runs-on: ubuntu-latest
-  #   needs: fetch-repo-topics
-  #   continue-on-error: true
-  #   outputs:
-  #     copyright_failed: ${{ steps.set_output.outputs.failed }}
-  #   steps:
-  #     - uses: actions/checkout@v4
+  copyright-check:
+    name: Copyright Headers Check
+    permissions:
+      contents: read
+      packages: read
+    env:
+      GITHUB_ACTOR: ${{ secrets.COMMON_USER }}
+      GITHUB_TOKEN: ${{ secrets.COMMON_USER_TOKEN }}
+    runs-on: ubuntu-latest
+    needs: fetch-repo-topics
+    continue-on-error: true
+    outputs:
+      copyright_failed: ${{ steps.set_output.outputs.failed }}
+    steps:
+      - uses: actions/checkout@v4
 
-  #     - name: Fetch Centralized Licenserc File
-  #       run: |
-  #         git clone https://x-access-token:${{ secrets.COMMON_USER_TOKEN }}@github.com/sampathbankplc/pipeline-config.git pipeline-configs
-  #         cp pipeline-configs/centralized-configs/.licenserc.yaml .github/.licenserc.yaml
+      - name: Fetch Centralized Licenserc File
+        run: |
+          git clone https://x-access-token:${{ secrets.COMMON_USER_TOKEN }}@github.com/sampathbankplc/pipeline-config.git pipeline-configs
+          cp pipeline-configs/centralized-configs/.licenserc.yaml .github/.licenserc.yaml
 
-  #     - name: Check copyright header
-  #       id: check
-  #       uses: apache/skywalking-eyes/header@v0.7.0
-  #       continue-on-error: true
-  #       with:
-  #         config: .github/.licenserc.yaml
-  #         mode: check
+      - name: Check copyright header
+        id: check
+        uses: apache/skywalking-eyes/header@v0.7.0
+        continue-on-error: true
+        with:
+          config: .github/.licenserc.yaml
+          mode: check
 
-  #     - name: Set Output for Copyright Check
-  #       id: set_output
-  #       run: |
-  #         if [[ "${{ steps.check.outcome }}" == "failure" ]]; then
-  #           echo "failed=true" >> $GITHUB_OUTPUT
-  #           exit 1
-  #         else
-  #           echo "failed=false" >> $GITHUB_OUTPUT
-  #         fi
+      - name: Set Output for Copyright Check
+        id: set_output
+        run: |
+          if [[ "${{ steps.check.outcome }}" == "failure" ]]; then
+            echo "failed=true" >> $GITHUB_OUTPUT
+            exit 1
+          else
+            echo "failed=false" >> $GITHUB_OUTPUT
+          fi
 
   code-formatting-check:
     name: Code Formatting Check
@@ -109,20 +108,15 @@ jobs:
       formatting_failed: ${{ steps.set_output.outputs.failed }}
     steps:
       - uses: actions/checkout@v4
-
-      - name: Setup .NET
-        uses: actions/setup-dotnet@v4
+      - uses: actions/setup-java@v3
         with:
-          dotnet-version: '9.0.305'
+          distribution: 'adopt'
+          java-version: '17'
 
-      - name: Restore dependencies
-        run: dotnet restore
-
-      - name: Run Format Check
+      - name: Run Spotless Check
         continue-on-error: true
-        id: format
-        run: dotnet format --verify-no-changes
-
+        id: spotless
+        run: mvn spotless:check
 
       - name: Set Output for Code Formatting Check
         id: set_output
@@ -136,7 +130,7 @@ jobs:
 
   prepare-workspace:
     name: Prepare Build Workspace
-    runs-on: ubuntu-latest
+    runs-on: [self-hosted, linux]
     outputs:
       workspace-path: ${{ steps.define_workspace.outputs.workspace }}
 
@@ -158,7 +152,7 @@ jobs:
 
   build-and-test:
     name: Build and Test
-    runs-on: ubuntu-latest
+    runs-on: [self-hosted, linux]
     needs: prepare-workspace
     env:
       WORKSPACE: ${{ needs.prepare-workspace.outputs.workspace-path }}
@@ -192,7 +186,7 @@ jobs:
     needs:
       - fetch-repo-topics
       - prepare-workspace
-      # - copyright-check
+      - copyright-check
       - code-formatting-check
       - build-and-test
     if: ${{ needs.fetch-repo-topics.outputs.topic_status != 'new' ||
@@ -241,7 +235,7 @@ jobs:
     needs:
       - fetch-repo-topics
       - prepare-workspace
-      # - copyright-check
+      - copyright-check
       - code-formatting-check
       - build-and-test
     if: ${{ needs.fetch-repo-topics.outputs.topic_status != 'new' ||
@@ -297,7 +291,7 @@ jobs:
     needs:
       - prepare-workspace
       - fetch-repo-topics
-      # - copyright-check
+      - copyright-check
       - code-formatting-check
       - build-and-test
       - fortify-vulnerability-scan
@@ -410,7 +404,7 @@ jobs:
 
   deploy:
     name: "Deploy Application"
-    runs-on: ubuntu-latest
+    runs-on: [self-hosted, linux]
     needs:
       - prepare-workspace
       - artifact-processing
@@ -452,7 +446,7 @@ jobs:
 
   post-deployment-verify:
     name: Post Deployment Verification
-    runs-on: ubuntu-latest
+    runs-on: [self-hosted, linux]
     needs:
       - deploy
       - pre-deploy-notify
@@ -485,7 +479,7 @@ jobs:
 
   smoke-test-verification:
     name: Smoke Test Verification
-    runs-on: ubuntu-latest
+    runs-on: [self-hosted, linux]
     needs:
 #      - prepare-workspace
       - post-deployment-verify
@@ -565,7 +559,7 @@ jobs:
 
   api-automation-verification:
     name: API Automation Verification
-    runs-on: ubuntu-latest
+    runs-on: [self-hosted, linux]
     needs:
 #      - prepare-workspace
       - post-deployment-verify
